#!/usr/bin/env bash
# Updates the plugin catalog block inside README.md from
# .claude-plugin/marketplace.json. The block is delimited by
# <!-- BEGIN: plugins-catalog ... --> ... <!-- END: plugins-catalog -->.
#
# Run from anywhere: ./scripts/update-readme-catalog.sh
#
# Requires: jq

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
manifest="$repo_root/.claude-plugin/marketplace.json"
readme="$repo_root/README.md"

if [[ ! -f "$manifest" ]]; then
  echo "error: $manifest not found" >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq is required (brew install jq)" >&2
  exit 1
fi

if [[ ! -f "$readme" ]]; then
  echo "error: $readme not found" >&2
  exit 1
fi

begin_marker="<!-- BEGIN: plugins-catalog (auto-generated by scripts/update-readme-catalog.sh — do not edit by hand) -->"
end_marker="<!-- END: plugins-catalog -->"

if ! grep -qF "$begin_marker" "$readme" || ! grep -qF "$end_marker" "$readme"; then
  echo "error: catalog markers not found in README.md" >&2
  echo "  expected: $begin_marker" >&2
  echo "  expected: $end_marker" >&2
  exit 1
fi

plugin_count=$(jq -r '.plugins | length' "$manifest")

if [[ "$plugin_count" -eq 0 ]]; then
  block=$'_No plugins yet — see [CONTRIBUTING.md](./CONTRIBUTING.md) to add the first one._'
else
  block=$(jq -r '
    [
      "| Plugin | Category | Description |",
      "|--------|----------|-------------|"
    ]
    + (
      .plugins
      | sort_by(.name)
      | map("| `\(.name)` | \(.category // "—") | \(.description // "") |")
    )
    | join("\n")
  ' "$manifest")
fi

tmp=$(mktemp)
block_file=$(mktemp)
printf '%s\n' "$block" > "$block_file"
awk -v begin="$begin_marker" -v end="$end_marker" -v block_file="$block_file" '
  $0 == begin {
    print
    while ((getline line < block_file) > 0) print line
    close(block_file)
    in_block = 1
    next
  }
  $0 == end   { in_block = 0; print; next }
  !in_block   { print }
' "$readme" > "$tmp"
mv "$tmp" "$readme"
rm -f "$block_file"

echo "updated README.md catalog (${plugin_count} plugin(s))"
